import reflex as rx

def projects():
    return rx.box(
        rx.vstack(
            rx.heading(
                "Projects",
                font_size="50px",
                text_align="center",
                margin_top="50px",
                
            ),
            rx.text(
                rx.fragment(
                    "Here you'll find some of the projects I've worked on. I've spent a lot of time studying and improving my programming logic by solving algorithms. Visual projects will continue to grow over time, but you can find many more repositories on my GitHub: ",
                    rx.link(
                        "havertzz04",
                        href="https://github.com/havertzz04",
                        color="cyan",
                        is_external=True
                    ),
                    "."
                ),
                text_align="center",
                margin_top="25px",
                max_width="1000px"
            ),
            align="center",
            justify="center",
        ),
        
        
        rx.center(
            rx.grid(
                rx.card(
                    rx.inset(
                        rx.image(
                            src="/space.png",
                            width="100%",
                            height="auto",
                        ),
                        side="top",
                        pb="current",
                    ),
                    rx.heading(
                        rx.fragment(
                            rx.link(
                                "Twitter Bot",
                                href="https://x.com/universe_images",
                                color="#F0FFFF",
                                is_external=True
                            ),
                        ),
                        text_align="center",
                        padding_top="10px"
                    ),
                    rx.text(
                        "Bot that daily posts a NASA Universe image to X automatically using the NASA API.",
                        text_align="center",
                        padding_top="10px"
                    ),
                    width="25vw",
                ),
                rx.card(
                    rx.inset(
                        rx.image(
                            src="/pokedex.png",
                            width="100%",
                            height="auto",
                        ),
                        side="top",
                        pb="current",
                    ),
                    rx.heading(
                        rx.fragment(
                            rx.link(
                                "Pokedex",
                                href="https://havertzz04.github.io/Pokedex/",
                                color="#F0FFFF",
                                is_external=True
                            ),
                        ),
                        text_align="center",
                        padding_top="10px"
                    ),
                    rx.text(
                        "Web Pokédex using Pokémon API to search and view each Pokémon's stats by name.",
                        text_align="center",
                        padding_top="10px"
                    ),
                    width="25vw",
                ),
                rx.card(
                    rx.inset(
                        rx.image(
                            src="/zz-player.png",
                            width="100%",
                            height="auto",
                        ),
                        side="top",
                        pb="current",
                    ),
                    rx.heading(
                        rx.fragment(
                            rx.link(
                                "ZZ-Player",
                                href="https://havertzz04.github.io/MP3-ZZ/",
                                color="#F0FFFF",
                                is_external=True
                            ),
                        ),
                        text_align="center",
                        padding_top="10px"
                    ),
                    rx.text(
                        "Mini music player with MP3 features like pause, shuffle, next, and previous—similar to Spotify using selected songs.",
                        text_align="center",
                        padding_top="10px"
                    ),
                    width="25vw",
                ),
                rx.card(
                    rx.inset(
                        rx.image(
                            src="/cr7.png",
                            width="100%",
                            height="auto",
                        ),
                        side="top",
                        pb="current",
                    ),
                    rx.heading(
                        rx.fragment(
                            rx.link(
                                "CR7 Website Fanatic",
                                href="https://havertzz04.github.io/CR7-Website-Fanatic/",
                                color="#F0FFFF",
                                is_external=True
                            ),
                        ),
                        text_align="center",
                        padding_top="10px"
                    ),
                    rx.text(
                        "Page created to practice layout design and JS modularization, also a small tribute to my favorite player CR7.",
                        text_align="center",
                        padding_top="10px"
                    ),
                    width="25vw",
                ),
                rx.card(
                    rx.inset(
                        rx.image(
                            src="/money.png",
                            width="100%",
                            height="auto",
                        ),
                        side="top",
                        pb="current",
                    ),
                    rx.heading(
                        rx.fragment(
                            rx.link(
                                "Money Assistance",
                                href="https://havertzz04.github.io/Money-Assistant/",
                                color="#F0FFFF",
                                is_external=True
                            ),
                        ),
                        text_align="center",
                        padding_top="10px"
                    ),
                    rx.text(
                        "Tool to add income and expenses, helping track and manage personal finances effectively.",
                        text_align="center",
                        padding_top="10px"
                    ),
                    width="25vw",
                ),
                rx.card(
                    rx.inset(
                        rx.image(
                            src="/pomodoro.png",
                            width="100%",
                            height="auto",
                        ),
                        side="top",
                        pb="current",
                    ),
                    rx.heading(
                        rx.fragment(
                            rx.link(
                                "Pomodoro Timer",
                                href="https://havertzz04.github.io/Weather-Forecaster/",
                                color="#F0FFFF",
                                is_external=True
                            ),
                        ),
                        text_align="center",
                        padding_top="10px"
                    ),
                    rx.text(
                        "I enjoy studying and productivity, so I built my own Pomodoro tool to manage my time effectively.",
                        text_align="center",
                        padding_top="10px"
                    ),
                    width="25vw",
                ),
                rx.card(
                    rx.inset(
                        rx.image(
                            src="/encryptor.png",
                            width="100%",
                            height="auto",
                        ),
                        side="top",
                        pb="current",
                    ),
                    rx.heading(
                        rx.fragment(
                            rx.link(
                                "Encryptor",
                                href="https://havertzz04.github.io/alura-encryptor/",
                                color="#F0FFFF",
                                is_external=True
                            ),
                        ),
                        text_align="center",
                        padding_top="10px"
                    ),
                    rx.text(
                        "This tool lets you encrypt and decrypt “important” texts lol",
                        text_align="center",
                        padding_top="10px"
                    ),
                    width="25vw",
                ),
                rx.card(
                    rx.inset(
                        rx.image(
                            src="/css.png",
                            width="100%",
                            height="auto",
                        ),
                        side="top",
                        pb="current",
                    ),
                    rx.heading(
                        rx.fragment(
                            rx.link(
                                "Contact Form Template",
                                href="https://havertzz04.github.io/Actividad_Maquetacion/",
                                color="#F0FFFF",
                                is_external=True
                            ),
                        ),
                        text_align="center",
                        padding_top="10px"
                    ),
                    rx.text(
                        "I took an HTML form and added full design and color to create this piece.",
                        text_align="center",
                        padding_top="10px"
                    ),
                    width="25vw",
                ),
                rx.card(
                    rx.inset(
                        rx.image(
                            src="/bmi.png",
                            width="100%",
                            height="auto",
                        ),
                        side="top",
                        pb="current",
                    ),
                    rx.heading(
                        rx.fragment(
                            rx.link(
                                "Body Mass Index",
                                href="https://havertzz04.github.io/BMI-Body-Mass-Index/",
                                color="#F0FFFF",
                                is_external=True
                            ),
                        ),
                        text_align="center",
                        padding_top="10px"
                    ),
                    rx.text(
                        "One of my first projects, made while I went to the gym, to calculate my BMI and my friends’.",
                        text_align="center",
                        padding_top="10px"
                    ),
                    width="25vw",
                ),
                columns="3",
                spacing="4",
                margin_top="50px",
                max_width="90vw",
            )
        ),
        bg="#010B13",
        padding="1em",
        width="100%",
        margin_top="100px",
        padding_bottom="75px",
        id="projects"
        
    )
